spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  datasource-log:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
    maximum-pool-size: 5
  h2:
    console:
      enabled: true
management:
  info:
    git:
      mode: full
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
security:
  jwt:
    token:
      issuer: security.jwt.token.issuer
      secret-key: pyro-secret-key
      access-expire-length: 864000000
      refresh-expire-length: 31622400000
