spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
    open-in-view: false
  datasource:
    url: jdbc:mariadb://stage-rds.cccyz8gf6rjw.us-west-2.rds.amazonaws.com:3306/mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: manager
    password: managerPassword
    hikari:
      maximum-pool-size: 5
  datasource-log:
    url: jdbc:mariadb://stage-rds.cccyz8gf6rjw.us-west-2.rds.amazonaws.com:3306/mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: manager
    password: managerPassword
    maximum-pool-size: 5
logging:
  config: classpath:log4j2-stage.yml
management:
  info:
    git:
      mode: full
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
security:
  jwt:
    token:
      issuer: security.jwt.token.issuer
      secret-key: pyro-secret-key
      access-expire-length: 864000000
      refresh-expire-length: 31622400000
