version: "3"
services:
  db:
    image: mariadb:1.0
    platform: linux/x86_64
    container_name: mariadb-1.0
    build:
      context: .
      dockerfile: ./Dockerfile.mariadb
    ports:
      - "12345:3306"
    restart: always
